import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClientProvider } from "@/contexts/query-client-provider";
import { UserProvider } from "@/contexts/app/user-provider";
import { User } from "@repo/api-types";
import { apiClient } from "@/lib/api-client";
import { redirect } from "next/navigation";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  var user: User | null;
  try {
    const res = await apiClient.get("/users/@me/", {
      headers: { Authorization: `Bearer ${cookies().get("token")?.value}` },
    });
    user = res.data;
  } catch (e) {
    user = null;
  }

  return (
    <html lang="en">
      <body className={`${inter.className} antialiased dark`}>
        <QueryClientProvider>
          <UserProvider>{children}</UserProvider>
        </QueryClientProvider>
        <div id="call-portal" />
      </body>
    </html>
  );
}
